
package ru.shaplov.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ItemWebService", targetNamespace = "http://ws.shaplov.ru/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ItemWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns ru.shaplov.ws.Item
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.shaplov.ru/ItemWebService/getRequest", output = "http://ws.shaplov.ru/ItemWebService/getResponse")
    public Item get(
        @WebParam(name = "arg0", partName = "arg0")
        Item arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.shaplov.ws.Item
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.shaplov.ru/ItemWebService/updateRequest", output = "http://ws.shaplov.ru/ItemWebService/updateResponse")
    public Item update(
        @WebParam(name = "arg0", partName = "arg0")
        Item arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://ws.shaplov.ru/ItemWebService/deleteRequest", output = "http://ws.shaplov.ru/ItemWebService/deleteResponse")
    public void delete(
        @WebParam(name = "arg0", partName = "arg0")
        Item arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.shaplov.ws.Item
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.shaplov.ru/ItemWebService/saveRequest", output = "http://ws.shaplov.ru/ItemWebService/saveResponse")
    public Item save(
        @WebParam(name = "arg0", partName = "arg0")
        Item arg0);

    /**
     * 
     * @return
     *     returns ru.shaplov.ws.ItemArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.shaplov.ru/ItemWebService/getItemsRequest", output = "http://ws.shaplov.ru/ItemWebService/getItemsResponse")
    public ItemArray getItems();

}
