
package ru.shaplov.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ItemWebServiceService", targetNamespace = "http://ws.shaplov.ru/", wsdlLocation = "http://localhost:8080/car_sales/ws/itemService?wsdl")
public class ItemWebServiceService
    extends Service {

    private final static URL ITEMWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ITEMWEBSERVICESERVICE_EXCEPTION;
    private final static QName ITEMWEBSERVICESERVICE_QNAME = new QName("http://ws.shaplov.ru/", "ItemWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/car_sales/ws/itemService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITEMWEBSERVICESERVICE_WSDL_LOCATION = url;
        ITEMWEBSERVICESERVICE_EXCEPTION = e;
    }

    public ItemWebServiceService() {
        super(getWsdlLocation(), ITEMWEBSERVICESERVICE_QNAME);
    }

    public ItemWebServiceService(WebServiceFeature... features) {
        super(getWsdlLocation(), ITEMWEBSERVICESERVICE_QNAME, features);
    }

    public ItemWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, ITEMWEBSERVICESERVICE_QNAME);
    }

    public ItemWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITEMWEBSERVICESERVICE_QNAME, features);
    }

    public ItemWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItemWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ItemWebService
     */
    @WebEndpoint(name = "ItemWebServicePort")
    public ItemWebService getItemWebServicePort() {
        return super.getPort(new QName("http://ws.shaplov.ru/", "ItemWebServicePort"), ItemWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemWebService
     */
    @WebEndpoint(name = "ItemWebServicePort")
    public ItemWebService getItemWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.shaplov.ru/", "ItemWebServicePort"), ItemWebService.class, features);
    }

    private static URL getWsdlLocation() {
        if (ITEMWEBSERVICESERVICE_EXCEPTION != null) {
            throw ITEMWEBSERVICESERVICE_EXCEPTION;
        }
        return ITEMWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
