
package ru.shaplov.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserWebServiceService", targetNamespace = "http://ws.shaplov.ru/", wsdlLocation = "http://localhost:8080/car_sales/ws/userService?wsdl")
public class UserWebServiceService
    extends Service {

    private final static URL USERWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException USERWEBSERVICESERVICE_EXCEPTION;
    private final static QName USERWEBSERVICESERVICE_QNAME = new QName("http://ws.shaplov.ru/", "UserWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/car_sales/ws/userService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERWEBSERVICESERVICE_WSDL_LOCATION = url;
        USERWEBSERVICESERVICE_EXCEPTION = e;
    }

    public UserWebServiceService() {
        super(getWsdlLocation(), USERWEBSERVICESERVICE_QNAME);
    }

    public UserWebServiceService(WebServiceFeature... features) {
        super(getWsdlLocation(), USERWEBSERVICESERVICE_QNAME, features);
    }

    public UserWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, USERWEBSERVICESERVICE_QNAME);
    }

    public UserWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERWEBSERVICESERVICE_QNAME, features);
    }

    public UserWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserWebService
     */
    @WebEndpoint(name = "UserWebServicePort")
    public UserWebService getUserWebServicePort() {
        return super.getPort(new QName("http://ws.shaplov.ru/", "UserWebServicePort"), UserWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserWebService
     */
    @WebEndpoint(name = "UserWebServicePort")
    public UserWebService getUserWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.shaplov.ru/", "UserWebServicePort"), UserWebService.class, features);
    }

    private static URL getWsdlLocation() {
        if (USERWEBSERVICESERVICE_EXCEPTION != null) {
            throw USERWEBSERVICESERVICE_EXCEPTION;
        }
        return USERWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
