# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

jdk: openjdk11

services:
  - postgresql

before_install:
  - psql -c 'create database car_catalog;' -U postgres
  - psql -c 'create database hiber;' -U postgres

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    CODECOV_TOKEN="e19274eb-82aa-4dfe-97cc-124d5c6fd922"

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - shaplovd@gmail.com
    on_success: never # default: change
    on_failure: always # default: always